config setup
    logfile=/var/log/libreswan/pluto.log
    logappend=no
    plutodebug=all
    dumpdir=/var/log/libreswan
    nhelpers=0

conn client
    keyexchange=ikev2
    authby=secret
    left=172.29.0.10
    leftid=@responder
    right=%any
    rightid=@initiator
    auto=add
