config setup
    logfile=/var/log/libreswan/pluto.log
    logappend=no
    plutodebug=all
    dumpdir=/var/log/libreswan

conn client
    keyexchange=ikev2
    authby=secret
    left=172.29.0.20
    leftid=@initiator
    right=172.29.0.10
    rightid=@responder
    auto=add
